PROBLEMS = [
    # Arrays & Hashing
    {"id": 1, "title": "Contains Duplicate", "category": "Arrays & Hashing", "difficulty": "Easy", "leetcode_slug": "contains-duplicate", "leetcode_id": 217},
    {"id": 2, "title": "Valid Anagram", "category": "Arrays & Hashing", "difficulty": "Easy", "leetcode_slug": "valid-anagram", "leetcode_id": 242},
    {"id": 3, "title": "Two Sum", "category": "Arrays & Hashing", "difficulty": "Easy", "leetcode_slug": "two-sum", "leetcode_id": 1},
    {"id": 4, "title": "Group Anagrams", "category": "Arrays & Hashing", "difficulty": "Medium", "leetcode_slug": "group-anagrams", "leetcode_id": 49},
    {"id": 5, "title": "Top K Frequent Elements", "category": "Arrays & Hashing", "difficulty": "Medium", "leetcode_slug": "top-k-frequent-elements", "leetcode_id": 347},
    {"id": 6, "title": "Encode and Decode Strings", "category": "Arrays & Hashing", "difficulty": "Medium", "leetcode_slug": "encode-and-decode-strings", "leetcode_id": 271},
    {"id": 7, "title": "Product of Array Except Self", "category": "Arrays & Hashing", "difficulty": "Medium", "leetcode_slug": "product-of-array-except-self", "leetcode_id": 238},
    {"id": 8, "title": "Valid Sudoku", "category": "Arrays & Hashing", "difficulty": "Medium", "leetcode_slug": "valid-sudoku", "leetcode_id": 36},
    {"id": 9, "title": "Longest Consecutive Sequence", "category": "Arrays & Hashing", "difficulty": "Medium", "leetcode_slug": "longest-consecutive-sequence", "leetcode_id": 128},
    # Two Pointers
    {"id": 10, "title": "Valid Palindrome", "category": "Two Pointers", "difficulty": "Easy", "leetcode_slug": "valid-palindrome", "leetcode_id": 125},
    {"id": 11, "title": "Two Sum II", "category": "Two Pointers", "difficulty": "Medium", "leetcode_slug": "two-sum-ii-input-array-is-sorted", "leetcode_id": 167},
    {"id": 12, "title": "3Sum", "category": "Two Pointers", "difficulty": "Medium", "leetcode_slug": "3sum", "leetcode_id": 15},
    {"id": 13, "title": "Container With Most Water", "category": "Two Pointers", "difficulty": "Medium", "leetcode_slug": "container-with-most-water", "leetcode_id": 11},
    {"id": 14, "title": "Trapping Rain Water", "category": "Two Pointers", "difficulty": "Hard", "leetcode_slug": "trapping-rain-water", "leetcode_id": 42},
    # Sliding Window
    {"id": 15, "title": "Best Time to Buy and Sell Stock", "category": "Sliding Window", "difficulty": "Easy", "leetcode_slug": "best-time-to-buy-and-sell-stock", "leetcode_id": 121},
    {"id": 16, "title": "Longest Substring Without Repeating Characters", "category": "Sliding Window", "difficulty": "Medium", "leetcode_slug": "longest-substring-without-repeating-characters", "leetcode_id": 3},
    {"id": 17, "title": "Longest Repeating Character Replacement", "category": "Sliding Window", "difficulty": "Medium", "leetcode_slug": "longest-repeating-character-replacement", "leetcode_id": 424},
    {"id": 18, "title": "Permutation in String", "category": "Sliding Window", "difficulty": "Medium", "leetcode_slug": "permutation-in-string", "leetcode_id": 567},
    {"id": 19, "title": "Minimum Window Substring", "category": "Sliding Window", "difficulty": "Hard", "leetcode_slug": "minimum-window-substring", "leetcode_id": 76},
    {"id": 20, "title": "Sliding Window Maximum", "category": "Sliding Window", "difficulty": "Hard", "leetcode_slug": "sliding-window-maximum", "leetcode_id": 239},
    # Stack
    {"id": 21, "title": "Valid Parentheses", "category": "Stack", "difficulty": "Easy", "leetcode_slug": "valid-parentheses", "leetcode_id": 20},
    {"id": 22, "title": "Min Stack", "category": "Stack", "difficulty": "Medium", "leetcode_slug": "min-stack", "leetcode_id": 155},
    {"id": 23, "title": "Evaluate Reverse Polish Notation", "category": "Stack", "difficulty": "Medium", "leetcode_slug": "evaluate-reverse-polish-notation", "leetcode_id": 150},
    {"id": 24, "title": "Generate Parentheses", "category": "Stack", "difficulty": "Medium", "leetcode_slug": "generate-parentheses", "leetcode_id": 22},
    {"id": 25, "title": "Daily Temperatures", "category": "Stack", "difficulty": "Medium", "leetcode_slug": "daily-temperatures", "leetcode_id": 739},
    {"id": 26, "title": "Car Fleet", "category": "Stack", "difficulty": "Medium", "leetcode_slug": "car-fleet", "leetcode_id": 853},
    {"id": 27, "title": "Largest Rectangle in Histogram", "category": "Stack", "difficulty": "Hard", "leetcode_slug": "largest-rectangle-in-histogram", "leetcode_id": 84},
    # Binary Search
    {"id": 28, "title": "Binary Search", "category": "Binary Search", "difficulty": "Easy", "leetcode_slug": "binary-search", "leetcode_id": 704},
    {"id": 29, "title": "Search a 2D Matrix", "category": "Binary Search", "difficulty": "Medium", "leetcode_slug": "search-a-2d-matrix", "leetcode_id": 74},
    {"id": 30, "title": "Koko Eating Bananas", "category": "Binary Search", "difficulty": "Medium", "leetcode_slug": "koko-eating-bananas", "leetcode_id": 875},
    {"id": 31, "title": "Find Minimum in Rotated Sorted Array", "category": "Binary Search", "difficulty": "Medium", "leetcode_slug": "find-minimum-in-rotated-sorted-array", "leetcode_id": 153},
    {"id": 32, "title": "Search in Rotated Sorted Array", "category": "Binary Search", "difficulty": "Medium", "leetcode_slug": "search-in-rotated-sorted-array", "leetcode_id": 33},
    {"id": 33, "title": "Time Based Key-Value Store", "category": "Binary Search", "difficulty": "Medium", "leetcode_slug": "time-based-key-value-store", "leetcode_id": 981},
    {"id": 34, "title": "Median of Two Sorted Arrays", "category": "Binary Search", "difficulty": "Hard", "leetcode_slug": "median-of-two-sorted-arrays", "leetcode_id": 4},
    # Linked List
    {"id": 35, "title": "Reverse Linked List", "category": "Linked List", "difficulty": "Easy", "leetcode_slug": "reverse-linked-list", "leetcode_id": 206},
    {"id": 36, "title": "Merge Two Sorted Lists", "category": "Linked List", "difficulty": "Easy", "leetcode_slug": "merge-two-sorted-lists", "leetcode_id": 21},
    {"id": 37, "title": "Reorder List", "category": "Linked List", "difficulty": "Medium", "leetcode_slug": "reorder-list", "leetcode_id": 143},
    {"id": 38, "title": "Remove Nth Node From End of List", "category": "Linked List", "difficulty": "Medium", "leetcode_slug": "remove-nth-node-from-end-of-list", "leetcode_id": 19},
    {"id": 39, "title": "Copy List with Random Pointer", "category": "Linked List", "difficulty": "Medium", "leetcode_slug": "copy-list-with-random-pointer", "leetcode_id": 138},
    {"id": 40, "title": "Add Two Numbers", "category": "Linked List", "difficulty": "Medium", "leetcode_slug": "add-two-numbers", "leetcode_id": 2},
    {"id": 41, "title": "Linked List Cycle", "category": "Linked List", "difficulty": "Easy", "leetcode_slug": "linked-list-cycle", "leetcode_id": 141},
    {"id": 42, "title": "Find the Duplicate Number", "category": "Linked List", "difficulty": "Medium", "leetcode_slug": "find-the-duplicate-number", "leetcode_id": 287},
    {"id": 43, "title": "LRU Cache", "category": "Linked List", "difficulty": "Medium", "leetcode_slug": "lru-cache", "leetcode_id": 146},
    {"id": 44, "title": "Merge K Sorted Lists", "category": "Linked List", "difficulty": "Hard", "leetcode_slug": "merge-k-sorted-lists", "leetcode_id": 23},
    {"id": 45, "title": "Reverse Nodes in K-Group", "category": "Linked List", "difficulty": "Hard", "leetcode_slug": "reverse-nodes-in-k-group", "leetcode_id": 25},
    # Trees
    {"id": 46, "title": "Invert Binary Tree", "category": "Trees", "difficulty": "Easy", "leetcode_slug": "invert-binary-tree", "leetcode_id": 226},
    {"id": 47, "title": "Maximum Depth of Binary Tree", "category": "Trees", "difficulty": "Easy", "leetcode_slug": "maximum-depth-of-binary-tree", "leetcode_id": 104},
    {"id": 48, "title": "Diameter of Binary Tree", "category": "Trees", "difficulty": "Easy", "leetcode_slug": "diameter-of-binary-tree", "leetcode_id": 543},
    {"id": 49, "title": "Balanced Binary Tree", "category": "Trees", "difficulty": "Easy", "leetcode_slug": "balanced-binary-tree", "leetcode_id": 110},
    {"id": 50, "title": "Same Tree", "category": "Trees", "difficulty": "Easy", "leetcode_slug": "same-tree", "leetcode_id": 100},
    {"id": 51, "title": "Subtree of Another Tree", "category": "Trees", "difficulty": "Easy", "leetcode_slug": "subtree-of-another-tree", "leetcode_id": 572},
    {"id": 52, "title": "Lowest Common Ancestor of BST", "category": "Trees", "difficulty": "Medium", "leetcode_slug": "lowest-common-ancestor-of-a-binary-search-tree", "leetcode_id": 235},
    {"id": 53, "title": "Binary Tree Level Order Traversal", "category": "Trees", "difficulty": "Medium", "leetcode_slug": "binary-tree-level-order-traversal", "leetcode_id": 102},
    {"id": 54, "title": "Binary Tree Right Side View", "category": "Trees", "difficulty": "Medium", "leetcode_slug": "binary-tree-right-side-view", "leetcode_id": 199},
    {"id": 55, "title": "Count Good Nodes in Binary Tree", "category": "Trees", "difficulty": "Medium", "leetcode_slug": "count-good-nodes-in-binary-tree", "leetcode_id": 1448},
    {"id": 56, "title": "Validate Binary Search Tree", "category": "Trees", "difficulty": "Medium", "leetcode_slug": "validate-binary-search-tree", "leetcode_id": 98},
    {"id": 57, "title": "Kth Smallest Element in BST", "category": "Trees", "difficulty": "Medium", "leetcode_slug": "kth-smallest-element-in-a-bst", "leetcode_id": 230},
    {"id": 58, "title": "Construct Binary Tree from Preorder and Inorder", "category": "Trees", "difficulty": "Medium", "leetcode_slug": "construct-binary-tree-from-preorder-and-inorder-traversal", "leetcode_id": 105},
    {"id": 59, "title": "Binary Tree Maximum Path Sum", "category": "Trees", "difficulty": "Hard", "leetcode_slug": "binary-tree-maximum-path-sum", "leetcode_id": 124},
    {"id": 60, "title": "Serialize and Deserialize Binary Tree", "category": "Trees", "difficulty": "Hard", "leetcode_slug": "serialize-and-deserialize-binary-tree", "leetcode_id": 297},
    # Tries
    {"id": 61, "title": "Implement Trie", "category": "Tries", "difficulty": "Medium", "leetcode_slug": "implement-trie-prefix-tree", "leetcode_id": 208},
    {"id": 62, "title": "Design Add and Search Words Data Structure", "category": "Tries", "difficulty": "Medium", "leetcode_slug": "design-add-and-search-words-data-structure", "leetcode_id": 211},
    {"id": 63, "title": "Word Search II", "category": "Tries", "difficulty": "Hard", "leetcode_slug": "word-search-ii", "leetcode_id": 212},
    # Heap / Priority Queue
    {"id": 64, "title": "Kth Largest Element in a Stream", "category": "Heap / Priority Queue", "difficulty": "Easy", "leetcode_slug": "kth-largest-element-in-a-stream", "leetcode_id": 703},
    {"id": 65, "title": "Last Stone Weight", "category": "Heap / Priority Queue", "difficulty": "Easy", "leetcode_slug": "last-stone-weight", "leetcode_id": 1046},
    {"id": 66, "title": "K Closest Points to Origin", "category": "Heap / Priority Queue", "difficulty": "Medium", "leetcode_slug": "k-closest-points-to-origin", "leetcode_id": 973},
    {"id": 67, "title": "Kth Largest Element in an Array", "category": "Heap / Priority Queue", "difficulty": "Medium", "leetcode_slug": "kth-largest-element-in-an-array", "leetcode_id": 215},
    {"id": 68, "title": "Task Scheduler", "category": "Heap / Priority Queue", "difficulty": "Medium", "leetcode_slug": "task-scheduler", "leetcode_id": 621},
    {"id": 69, "title": "Design Twitter", "category": "Heap / Priority Queue", "difficulty": "Medium", "leetcode_slug": "design-twitter", "leetcode_id": 355},
    {"id": 70, "title": "Find Median from Data Stream", "category": "Heap / Priority Queue", "difficulty": "Hard", "leetcode_slug": "find-median-from-data-stream", "leetcode_id": 295},
    # Backtracking
    {"id": 71, "title": "Subsets", "category": "Backtracking", "difficulty": "Medium", "leetcode_slug": "subsets", "leetcode_id": 78},
    {"id": 72, "title": "Combination Sum", "category": "Backtracking", "difficulty": "Medium", "leetcode_slug": "combination-sum", "leetcode_id": 39},
    {"id": 73, "title": "Combination Sum II", "category": "Backtracking", "difficulty": "Medium", "leetcode_slug": "combination-sum-ii", "leetcode_id": 40},
    {"id": 74, "title": "Permutations", "category": "Backtracking", "difficulty": "Medium", "leetcode_slug": "permutations", "leetcode_id": 46},
    {"id": 75, "title": "Subsets II", "category": "Backtracking", "difficulty": "Medium", "leetcode_slug": "subsets-ii", "leetcode_id": 90},
    {"id": 76, "title": "Word Search", "category": "Backtracking", "difficulty": "Medium", "leetcode_slug": "word-search", "leetcode_id": 79},
    {"id": 77, "title": "Palindrome Partitioning", "category": "Backtracking", "difficulty": "Medium", "leetcode_slug": "palindrome-partitioning", "leetcode_id": 131},
    {"id": 78, "title": "Letter Combinations of a Phone Number", "category": "Backtracking", "difficulty": "Medium", "leetcode_slug": "letter-combinations-of-a-phone-number", "leetcode_id": 17},
    {"id": 79, "title": "N-Queens", "category": "Backtracking", "difficulty": "Hard", "leetcode_slug": "n-queens", "leetcode_id": 51},
    # Graphs
    {"id": 80, "title": "Number of Islands", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "number-of-islands", "leetcode_id": 200},
    {"id": 81, "title": "Clone Graph", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "clone-graph", "leetcode_id": 133},
    {"id": 82, "title": "Max Area of Island", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "max-area-of-island", "leetcode_id": 695},
    {"id": 83, "title": "Pacific Atlantic Water Flow", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "pacific-atlantic-water-flow", "leetcode_id": 417},
    {"id": 84, "title": "Surrounded Regions", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "surrounded-regions", "leetcode_id": 130},
    {"id": 85, "title": "Rotting Oranges", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "rotting-oranges", "leetcode_id": 994},
    {"id": 86, "title": "Walls and Gates", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "walls-and-gates", "leetcode_id": 286},
    {"id": 87, "title": "Course Schedule", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "course-schedule", "leetcode_id": 207},
    {"id": 88, "title": "Course Schedule II", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "course-schedule-ii", "leetcode_id": 210},
    {"id": 89, "title": "Redundant Connection", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "redundant-connection", "leetcode_id": 684},
    {"id": 90, "title": "Number of Connected Components", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "number-of-connected-components-in-an-undirected-graph", "leetcode_id": 323},
    {"id": 91, "title": "Graph Valid Tree", "category": "Graphs", "difficulty": "Medium", "leetcode_slug": "graph-valid-tree", "leetcode_id": 261},
    {"id": 92, "title": "Word Ladder", "category": "Graphs", "difficulty": "Hard", "leetcode_slug": "word-ladder", "leetcode_id": 127},
    # Advanced Graphs
    {"id": 93, "title": "Reconstruct Itinerary", "category": "Advanced Graphs", "difficulty": "Hard", "leetcode_slug": "reconstruct-itinerary", "leetcode_id": 332},
    {"id": 94, "title": "Min Cost to Connect All Points", "category": "Advanced Graphs", "difficulty": "Medium", "leetcode_slug": "min-cost-to-connect-all-points", "leetcode_id": 1584},
    {"id": 95, "title": "Network Delay Time", "category": "Advanced Graphs", "difficulty": "Medium", "leetcode_slug": "network-delay-time", "leetcode_id": 743},
    {"id": 96, "title": "Swim in Rising Water", "category": "Advanced Graphs", "difficulty": "Hard", "leetcode_slug": "swim-in-rising-water", "leetcode_id": 778},
    {"id": 97, "title": "Alien Dictionary", "category": "Advanced Graphs", "difficulty": "Hard", "leetcode_slug": "alien-dictionary", "leetcode_id": 269},
    {"id": 98, "title": "Cheapest Flights Within K Stops", "category": "Advanced Graphs", "difficulty": "Medium", "leetcode_slug": "cheapest-flights-within-k-stops", "leetcode_id": 787},
    # 1D Dynamic Programming
    {"id": 99, "title": "Climbing Stairs", "category": "1D DP", "difficulty": "Easy", "leetcode_slug": "climbing-stairs", "leetcode_id": 70},
    {"id": 100, "title": "Min Cost Climbing Stairs", "category": "1D DP", "difficulty": "Easy", "leetcode_slug": "min-cost-climbing-stairs", "leetcode_id": 746},
    {"id": 101, "title": "House Robber", "category": "1D DP", "difficulty": "Medium", "leetcode_slug": "house-robber", "leetcode_id": 198},
    {"id": 102, "title": "House Robber II", "category": "1D DP", "difficulty": "Medium", "leetcode_slug": "house-robber-ii", "leetcode_id": 213},
    {"id": 103, "title": "Longest Palindromic Substring", "category": "1D DP", "difficulty": "Medium", "leetcode_slug": "longest-palindromic-substring", "leetcode_id": 5},
    {"id": 104, "title": "Palindromic Substrings", "category": "1D DP", "difficulty": "Medium", "leetcode_slug": "palindromic-substrings", "leetcode_id": 647},
    {"id": 105, "title": "Decode Ways", "category": "1D DP", "difficulty": "Medium", "leetcode_slug": "decode-ways", "leetcode_id": 91},
    {"id": 106, "title": "Coin Change", "category": "1D DP", "difficulty": "Medium", "leetcode_slug": "coin-change", "leetcode_id": 322},
    {"id": 107, "title": "Maximum Product Subarray", "category": "1D DP", "difficulty": "Medium", "leetcode_slug": "maximum-product-subarray", "leetcode_id": 152},
    {"id": 108, "title": "Word Break", "category": "1D DP", "difficulty": "Medium", "leetcode_slug": "word-break", "leetcode_id": 139},
    {"id": 109, "title": "Longest Increasing Subsequence", "category": "1D DP", "difficulty": "Medium", "leetcode_slug": "longest-increasing-subsequence", "leetcode_id": 300},
    {"id": 110, "title": "Partition Equal Subset Sum", "category": "1D DP", "difficulty": "Medium", "leetcode_slug": "partition-equal-subset-sum", "leetcode_id": 416},
    # 2D Dynamic Programming
    {"id": 111, "title": "Unique Paths", "category": "2D DP", "difficulty": "Medium", "leetcode_slug": "unique-paths", "leetcode_id": 62},
    {"id": 112, "title": "Longest Common Subsequence", "category": "2D DP", "difficulty": "Medium", "leetcode_slug": "longest-common-subsequence", "leetcode_id": 1143},
    {"id": 113, "title": "Best Time to Buy and Sell Stock with Cooldown", "category": "2D DP", "difficulty": "Medium", "leetcode_slug": "best-time-to-buy-and-sell-stock-with-cooldown", "leetcode_id": 309},
    {"id": 114, "title": "Coin Change II", "category": "2D DP", "difficulty": "Medium", "leetcode_slug": "coin-change-ii", "leetcode_id": 518},
    {"id": 115, "title": "Target Sum", "category": "2D DP", "difficulty": "Medium", "leetcode_slug": "target-sum", "leetcode_id": 494},
    {"id": 116, "title": "Interleaving String", "category": "2D DP", "difficulty": "Medium", "leetcode_slug": "interleaving-string", "leetcode_id": 97},
    {"id": 117, "title": "Longest Increasing Path in a Matrix", "category": "2D DP", "difficulty": "Hard", "leetcode_slug": "longest-increasing-path-in-a-matrix", "leetcode_id": 329},
    {"id": 118, "title": "Distinct Subsequences", "category": "2D DP", "difficulty": "Hard", "leetcode_slug": "distinct-subsequences", "leetcode_id": 115},
    {"id": 119, "title": "Edit Distance", "category": "2D DP", "difficulty": "Medium", "leetcode_slug": "edit-distance", "leetcode_id": 72},
    {"id": 120, "title": "Burst Balloons", "category": "2D DP", "difficulty": "Hard", "leetcode_slug": "burst-balloons", "leetcode_id": 312},
    {"id": 121, "title": "Regular Expression Matching", "category": "2D DP", "difficulty": "Hard", "leetcode_slug": "regular-expression-matching", "leetcode_id": 10},
    # Greedy
    {"id": 122, "title": "Maximum Subarray", "category": "Greedy", "difficulty": "Medium", "leetcode_slug": "maximum-subarray", "leetcode_id": 53},
    {"id": 123, "title": "Jump Game", "category": "Greedy", "difficulty": "Medium", "leetcode_slug": "jump-game", "leetcode_id": 55},
    {"id": 124, "title": "Jump Game II", "category": "Greedy", "difficulty": "Medium", "leetcode_slug": "jump-game-ii", "leetcode_id": 45},
    {"id": 125, "title": "Gas Station", "category": "Greedy", "difficulty": "Medium", "leetcode_slug": "gas-station", "leetcode_id": 134},
    {"id": 126, "title": "Hand of Straights", "category": "Greedy", "difficulty": "Medium", "leetcode_slug": "hand-of-straights", "leetcode_id": 846},
    {"id": 127, "title": "Merge Triplets to Form Target Triplet", "category": "Greedy", "difficulty": "Medium", "leetcode_slug": "merge-triplets-to-form-target-triplet", "leetcode_id": 1899},
    {"id": 128, "title": "Partition Labels", "category": "Greedy", "difficulty": "Medium", "leetcode_slug": "partition-labels", "leetcode_id": 763},
    {"id": 129, "title": "Valid Parenthesis String", "category": "Greedy", "difficulty": "Medium", "leetcode_slug": "valid-parenthesis-string", "leetcode_id": 678},
    # Intervals
    {"id": 130, "title": "Insert Interval", "category": "Intervals", "difficulty": "Medium", "leetcode_slug": "insert-interval", "leetcode_id": 57},
    {"id": 131, "title": "Merge Intervals", "category": "Intervals", "difficulty": "Medium", "leetcode_slug": "merge-intervals", "leetcode_id": 56},
    {"id": 132, "title": "Non-overlapping Intervals", "category": "Intervals", "difficulty": "Medium", "leetcode_slug": "non-overlapping-intervals", "leetcode_id": 435},
    {"id": 133, "title": "Meeting Rooms", "category": "Intervals", "difficulty": "Easy", "leetcode_slug": "meeting-rooms", "leetcode_id": 252},
    {"id": 134, "title": "Meeting Rooms II", "category": "Intervals", "difficulty": "Medium", "leetcode_slug": "meeting-rooms-ii", "leetcode_id": 253},
    {"id": 135, "title": "Minimum Interval to Include Each Query", "category": "Intervals", "difficulty": "Hard", "leetcode_slug": "minimum-interval-to-include-each-query", "leetcode_id": 1851},
    # Math & Geometry
    {"id": 136, "title": "Rotate Image", "category": "Math & Geometry", "difficulty": "Medium", "leetcode_slug": "rotate-image", "leetcode_id": 48},
    {"id": 137, "title": "Spiral Matrix", "category": "Math & Geometry", "difficulty": "Medium", "leetcode_slug": "spiral-matrix", "leetcode_id": 54},
    {"id": 138, "title": "Set Matrix Zeroes", "category": "Math & Geometry", "difficulty": "Medium", "leetcode_slug": "set-matrix-zeroes", "leetcode_id": 73},
    {"id": 139, "title": "Happy Number", "category": "Math & Geometry", "difficulty": "Easy", "leetcode_slug": "happy-number", "leetcode_id": 202},
    {"id": 140, "title": "Plus One", "category": "Math & Geometry", "difficulty": "Easy", "leetcode_slug": "plus-one", "leetcode_id": 66},
    {"id": 141, "title": "Pow(x, n)", "category": "Math & Geometry", "difficulty": "Medium", "leetcode_slug": "powx-n", "leetcode_id": 50},
    {"id": 142, "title": "Multiply Strings", "category": "Math & Geometry", "difficulty": "Medium", "leetcode_slug": "multiply-strings", "leetcode_id": 43},
    {"id": 143, "title": "Detect Squares", "category": "Math & Geometry", "difficulty": "Medium", "leetcode_slug": "detect-squares", "leetcode_id": 2013},
    # Bit Manipulation
    {"id": 144, "title": "Single Number", "category": "Bit Manipulation", "difficulty": "Easy", "leetcode_slug": "single-number", "leetcode_id": 136},
    {"id": 145, "title": "Number of 1 Bits", "category": "Bit Manipulation", "difficulty": "Easy", "leetcode_slug": "number-of-1-bits", "leetcode_id": 191},
    {"id": 146, "title": "Counting Bits", "category": "Bit Manipulation", "difficulty": "Easy", "leetcode_slug": "counting-bits", "leetcode_id": 338},
    {"id": 147, "title": "Reverse Bits", "category": "Bit Manipulation", "difficulty": "Easy", "leetcode_slug": "reverse-bits", "leetcode_id": 190},
    {"id": 148, "title": "Missing Number", "category": "Bit Manipulation", "difficulty": "Easy", "leetcode_slug": "missing-number", "leetcode_id": 268},
    {"id": 149, "title": "Sum of Two Integers", "category": "Bit Manipulation", "difficulty": "Medium", "leetcode_slug": "sum-of-two-integers", "leetcode_id": 371},
    {"id": 150, "title": "Reverse Integer", "category": "Bit Manipulation", "difficulty": "Medium", "leetcode_slug": "reverse-integer", "leetcode_id": 7},
]
